#format = """
#[╭─user───❯](bold blue) $username
#[┣─system─❯](bold yellow) $hostname
#[┣─project❯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
#[╰─cmd────❯](bold green) 
#"""
[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user@]($style)" 
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](green bold):'
trim_at = "."
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Replace the "❯" symbol in the prompt with "➜"
error_symbol = "[✗](bold red)"
#  
# configure directory
[directory]
read_only = " "
truncation_length = 2
truncation_symbol = '.../' 
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
detect_extensions = ['c', 'h', 'cc', 'hh', 'cpp']

[cmd_duration]
min_time = 4000
show_milliseconds = false
disabled = false
style = "bold italic red"


[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\]'

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = "󰍛 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = " "
#pyenv_version_name = true
format = '\[[${symbol}python (${version})(\($virtualenv\))]($style)\]'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"


[custom.lammps]
detect_extensions = ['in', 'lmp']
symbol = " "
format = '\[[${symbol}LAMMPS]($style)\]'
style = "bold green"

